### ISSUE TITLE
Why use invoke() instead of a method call for the same connection

### ISSUE THREAD

**Issue by wanlinus** [efenderbosch/spring-boot-aws-cloudsearch#3]
Please forgive me for not having your contact information. I read spring-projects/spring-security-oauth code have some questions. In this class org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStore.storeAccessToken()
can use 'set()' method to set value , why use invoke() in same connection, What's the difference between them.I looked up a lot of information, but I couldn't find the answer. Can you tell me?

```java
if (springDataRedis_2_0) {
	try {
		this.redisConnectionSet_2_0.invoke(conn, accessKey, serializedAccessToken);
		this.redisConnectionSet_2_0.invoke(conn, authKey, serializedAuth);
		this.redisConnectionSet_2_0.invoke(conn, authToAccessKey, serializedAccessToken);
	} catch (Exception ex) {
		throw new RuntimeException(ex);
	}
} else {
	conn.set(accessKey, serializedAccessToken);
	conn.set(authKey, serializedAuth);
	conn.set(authToAccessKey, serializedAccessToken);
}

```

**Comment by efenderbosch** [comment]
I wrote the original `RedisTokenStore` years ago, sorry. And I think someone else added the `2_0` stuff. Sorry I don't know.
